api_platform:

    # The title of the API.
    title: 'Webee'

    # The description of the API.
    description: 'Api webee'

    # The version of the API.
    version: '1.0.0'

    # Enable ReDoc.
    enable_re_doc: true

    collection:
        pagination:
            page_parameter_name: 'page'
            enabled_parameter_name: 'pagination'
            items_per_page_parameter_name: 'itemsPerPage'

    mapping:
        paths: ['%kernel.project_dir%/config/api_platform/resources']

    # The list of your resources class directories. Defaults to the directories of the mapping paths but might differ.
    resource_class_directories:
        - '%kernel.project_dir%/src/Entity'


    swagger:
        # The active versions of OpenAPI to be exported or used in the swagger_ui. The first value is the default.
        versions: [3]
        api_keys:
            JWT:
                name: Authorization
                type: header

    openapi:
        # The contact information for the exposed API.
        contact:
            # The identifying name of the contact person/organization.
            name: Webee
            # The email address of the contact person/organization. MUST be in the format of an email address.
            email: webee@gmail.com

    # The list of enabled formats. The first one will be the default.
    formats:
        json:
            mime_types: ['application/json']
        jsonld:
            mime_types: ['application/ld+json']
        multipart:
            mime_types: ['multipart/form-data']
        html:
            mime_types: ['text/html']


    # The list of enabled patch formats. The first one will be the default.
    patch_formats:
        json: [ 'application/json' ]

    defaults:
        pagination_items_per_page: 30
        pagination_enabled: true
        pagination_client_enabled: true
        pagination_client_items_per_page: true
        normalization_context:
            skip_null_values: false
