liip_imagine:
    driver: "gd"

    filter_sets:
        web_filter:
            quality: 75
            filters:
                thumbnail: { size: [120, 90], mode: outbound }

        mobile_filter:
            quality: 75
            filters:
                thumbnail: { size: [60, 45], mode: outbound }