vich_uploader:
    db_driver: orm

    mappings:
        banner:
            uri_prefix: '%banner_image_dir_prefix%'
            upload_destination: '%banner_image_dir%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        user_upload:
            uri_prefix: '%user_image_dir_prefix%'
            upload_destination: '%user_image_dir%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
