vich_uploader:
    db_driver: orm

    mappings:
        banner:
            uri_prefix: banner_images
            upload_destination: '%kernel.project_dir%/public/banners/images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
