version: "3.8"
services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        user: www
        uid: 1000
    container_name: mokolos-php8
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www:delegated
    networks:
      - dev

  db:
    image: mysql:9.0.1
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
    volumes:
      - ./var:/var/lib/mysql
      - ./docker/web/config.conf:/etc/nginx/conf.d/default.conf
    networks:
      - dev

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
    networks:
      - dev

  nginx:
    image: nginx:alpine
    container_name: mokolos-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www:delegated
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
    networks:
      - dev

  node:
    image: node:20
    container_name: mokolos-node20
    restart: unless-stopped
    volumes:
      - ./:/var/www
    ports:
      - '5173:5173'
    working_dir: /var/www
    command: sh -c "tail -f /dev/null"
    networks:
      - dev

networks:
  dev:
    driver: bridge
