App\Entity\About:
  operations:
    get_about:
      class: ApiPlatform\Metadata\GetCollection
      method: GET
      security: 'is_granted("ROLE_USER")'


  normalizationContext:
    groups: [ 'about:read' ]