App\Entity\About:
  operations:
    get_about:
      class: ApiPlatform\Metadata\GetCollection
      method: GET
      security: 'is_granted("ROLE_API_USER")'
      securityMessage: "Only api user roles can access the abouts data."

  normalizationContext:
    groups: [ 'about:read' ]