App\Entity\About:
  operations:
    get_about:
      class: ApiPlatform\Metadata\GetCollection
      method: GET
      security: 'is_granted("ROLE_EMPLOYER")'
      securityMessage: "Only employer can get abouts."

  normalizationContext:
    groups: [ 'about:read' ]