App\Entity\Banner:
  operations:
    get_banners_web:
      class: ApiPlatform\Metadata\GetCollection
      method: GET
      uriTemplate: /banners/web
      security: 'is_granted("ROLE_EMPLOYER")'
      securityMessage: "Only employer roles can access the banners data."

    get_banners_mobile:
      class: ApiPlatform\Metadata\GetCollection
      method: GET
      uriTemplate: /banners/mobile
      security: 'is_granted("ROLE_EMPLOYER")'
      securityMessage: "Only employer can get banners."

  normalizationContext:
    groups: [ 'banner:read' ]