App\Entity\Banner:
  operations:
    get_banners_web:
      class: ApiPlatform\Metadata\GetCollection
      method: GET
      uriTemplate: /banners/web
      security: 'is_granted("ROLE_API_USER")'
      securityMessage: "Only api user roles can access the banners data web."

    get_banners_mobile:
      class: ApiPlatform\Metadata\GetCollection
      method: GET
      uriTemplate: /banners/mobile
      security: 'is_granted("ROLE_API_USER")'
      securityMessage: "Only api user roles can get banners data mobile."

  normalizationContext:
    groups: [ 'banner:read' ]