App\Entity\Faq:
  operations:
    get_faq:
      class: ApiPlatform\Metadata\GetCollection
      method: GET
      security: 'is_granted("ROLE_EMPLOYER")'
      securityMessage: 'Only employer roles can access the fAQs data.'

  normalizationContext:
    groups: [ 'faq:read' ]