App\Entity\Faq:
  operations:
    get_faq:
      class: ApiPlatform\Metadata\GetCollection
      method: GET
      security: 'is_granted("ROLE_USER")'


  normalizationContext:
    groups: [ 'faq:read' ]