App\Entity\Section:
  operations:
    get_section:
      class: ApiPlatform\Metadata\GetCollection
      method: GET
      security: 'is_granted("ROLE_EMPLOYER")'
      securityMessage: "Only employer roles can access the sections data."

  normalizationContext:
    groups: [ 'section:read' ]