App\Entity\Section:
  operations:
    get_section:
      class: ApiPlatform\Metadata\GetCollection
      method: GET
      security: 'is_granted("ROLE_USER")'


  normalizationContext:
    groups: [ 'section:read' ]