App\Entity\Service:
  operations:
    get_service:
      class: ApiPlatform\Metadata\GetCollection
      method: GET
      security: 'is_granted("ROLE_EMPLOYER")'
      securityMessage: "Only employer roles can access the services data."

  normalizationContext:
    groups: [ 'service:read' ]