App\Entity\Service:
  operations:
    get_service:
      class: ApiPlatform\Metadata\GetCollection
      method: GET
      security: 'is_granted("ROLE_USER")'


  normalizationContext:
    groups: [ 'service:read' ]