App\Entity\Technology:
  operations:
    get_technology:
      class: ApiPlatform\Metadata\GetCollection
      method: GET
      security: 'is_granted("ROLE_API_USER")'
      securityMessage: "Only api user roles can access the technology data."

  normalizationContext:
    groups: [ 'technology:read' ]