App\Entity\Technology:
  operations:
    get_technology:
      class: ApiPlatform\Metadata\GetCollection
      method: GET
      security: 'is_granted("ROLE_USER")'


  normalizationContext:
    groups: [ 'technology:read' ]