App\Entity\Technology:
  operations:
    get_technology:
      class: ApiPlatform\Metadata\GetCollection
      method: GET
      security: 'is_granted("ROLE_EMPLOYER")'
      securityMessage: "Only employer can get technology."


  normalizationContext:
    groups: [ 'technology:read' ]