App\Entity\User:
  operations:
    get_user:
      class: ApiPlatform\Metadata\GetCollection
      method: GET
      uriTemplate: /users
      security: 'is_granted("ROLE_API_USER")'
      securityMessage: "Only api user roles can access the Users data."
    post_update_user:
      class: ApiPlatform\Metadata\Post
      uriTemplate: /employee/update/password
      security: 'is_granted("ROLE_EMPLOYER")'
      securityMessage: 'Only employee roles can post the user data.'
      controller: App\Controller\UserUpdateController

  normalizationContext:
    groups: [ 'user:read' ]