App\Entity\User:
  operations:
    get_user:
      class: ApiPlatform\Metadata\GetCollection
      method: GET
      uriTemplate: /users
      security: 'is_granted("ROLE_EMPLOYER")'
      securityMessage: "Only employer can get users."


  normalizationContext:
    groups: [ 'user:read' ]