App\Entity\User:
  operations:
    get_user:
      class: ApiPlatform\Metadata\GetCollection
      method: GET
      uriTemplate: /users
      security: 'is_granted("ROLE_API_USER")'
      securityMessage: "Only api user roles can access the Users data."
    update_password_user:
      class: ApiPlatform\Metadata\Post
      uriTemplate: /employee/update/password
      controller: App\Controller\UpdatePasswordController
    forgot_password_user:
      class: ApiPlatform\Metadata\Post
      uriTemplate: /employee/forgot/password
      controller: App\Controller\ForgotPasswordController

  normalizationContext:
    groups: [ 'user:read' ]