App\Entity\User:
  operations:
    get_user:
      class: ApiPlatform\Metadata\GetCollection
      method: GET
      uriTemplate: /users
      security: 'is_granted("ROLE_API_USER")'
      securityMessage: "Only api user roles can access the Users data."

  normalizationContext:
    groups: [ 'user:read' ]