# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
imports:
    - { resource: parameters/ }}
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            string $permissionSheetId: '%env(GOOGLE_SHEET_PERMISSION_ID)%'
            string $holydaySheetId: '%env(GOOGLE_SHEET_HOLYDAY_ID)%'
            string $default_email: '%env(DEFAULT_EMAIL)%'
            string $app_url_front: '%env(APP_URL_FRONT)%'
            string $default_password_user: '%env(DEFAULT_PASSWORD_USER)%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\EventListener\BannerItemsListener:
        tags:
            - { name: kernel.event_listener, event: vich_uploader.post_upload }

    'App\Doctrine\UserExtension':
        tags:
            - { name: api_platform.doctrine.orm.query_extension.collection }
    App\Controller\AuthEmployerController:
        arguments:
            $userProvider: '@security.user.provider.concrete.app_user_provider'
    App\State\EmployeeEntitiesStateProcessor:
        bind:
            $persistProcessor: '@api_platform.doctrine.orm.state.persist_processor'
    App\EventSubscriber\EmployeeEntitiesSubscriber:
        tags:
            - { name: 'kernel.event_subscriber' }
    Symfony\Component\Mailer\Mailer:
        alias: 'mailer'
        public: true*
    App\Services\JWTService:
        arguments:
            $secretKey: '%env(APP_SECRET)%'
            $appUrl: '%env(APP_URL)%'