parameters:
  public_dir: '%kernel.project_dir%/public'
  banner_image_dir: '%public_dir%/%banner_image_dir_prefix%'

  image_dir_prefix: '/banners/images'
  banner_image_dir_prefix: '%image_dir_prefix%/web'
